const RESEARCH_PAPERS = [
  {
    id: "paper_001",
    shortName: "Lee et al.",
    fullTitle: "Hallucination by Code Generation LLMs: Taxonomy, Benchmarks, Mitigation, and Challenges",
    authors: "Lee, Song, Kim, Kim, Kim & Nam",
    year: "2025",
    focus: "Master taxonomy survey — four hallucination categories: Syntactic, Runtime Execution, Functional Correctness, Code Quality",
    hallucTypes: ["Fabricated Package", "Non-existent Method", "Fabricated API", "Wrong Syntax Confidence"],
    tag: "Taxonomy",
    link: "https://arxiv.org/abs/2504.20799"
  },
  {
    id: "paper_002",
    shortName: "CodeMirage",
    fullTitle: "CodeMirage: Hallucinations in Code Generated by Large Language Models",
    authors: "Mridha et al.",
    year: "2024",
    focus: "Identifies hallucination patterns in LLM-generated code, including fabricated APIs and packages",
    hallucTypes: ["Fabricated Package", "Fabricated API"],
    tag: "Detection",
    link: "https://arxiv.org/abs/2408.08333"
  },
  {
    id: "paper_003",
    shortName: "Chen et al. HumanEval",
    fullTitle: "Evaluating Large Language Models Trained on Code",
    authors: "Chen et al.",
    year: "2021",
    focus: "Introduces HumanEval — functional correctness benchmark for evaluating generated code against test cases",
    hallucTypes: ["Non-existent Method", "Wrong Syntax Confidence"],
    tag: "Benchmark",
    link: "https://arxiv.org/abs/2107.03374"
  },
  {
    id: "paper_004",
    shortName: "De-Hallucinator",
    fullTitle: "De-Hallucinator: Iterative Grounding for Hallucination Mitigation in Code Generation",
    authors: "Eghbali & Pradel",
    year: "2024",
    focus: "Retrieval-based iterative grounding to correct hallucinated API usage",
    hallucTypes: ["Fabricated API", "Non-existent Method"],
    tag: "Mitigation",
    link: "https://arxiv.org/abs/2401.01701"
  },
  {
    id: "paper_005",
    shortName: "Beyond Functional Correctness",
    fullTitle: "Exploring and Evaluating Hallucinations in LLM-Powered Code Generation",
    authors: "Liu et al.",
    year: "2024",
    focus: "Empirical study of hallucination patterns across multiple LLMs and programming languages",
    hallucTypes: ["Wrong Syntax Confidence", "Non-existent Method", "Fabricated Package"],
    tag: "Empirical Study",
    link: "https://arxiv.org/abs/2404.00971"
  },
  {
    id: "paper_006",
    shortName: "CodeBERT",
    fullTitle: "CodeBERT: A Pre-Trained Model for Programming and Natural Languages",
    authors: "Feng et al.",
    year: "2020",
    focus: "Pre-trained code representation model underlying many code-LLM detection and mitigation techniques",
    hallucTypes: ["Non-existent Method"],
    tag: "Code LLM",
    link: "https://arxiv.org/abs/2002.08155"
  }
];
  
