const RESEARCH_PAPERS = [

  {
    id: "paper_001",
    shortName: "CodeHalu",
    fullTitle: "CodeHalu: Hallucinations in Code Generated by Large Language Models",
    authors: "Tian et al.",
    year: "2024",
    focus: "Execution-based hallucination detection — runs code and checks output correctness",
    hallucTypes: ["Fabricated Package", "Non-existent Method"],
    tag: "Fabricated API",
    link: "https://arxiv.org/abs/2405.00253"
  },

  {
    id: "paper_002",
    shortName: "CodeMirage",
    fullTitle: "CodeMirage: Hallucinations in Code Generated by Large Language Models",
    authors: "Agarwal et al.",
    year: "2024",
    focus: "Identifies hallucination patterns in LLM-generated code through static analysis",
    hallucTypes: ["Wrong Syntax Confidence", "Fabricated Package"],
    tag: "Static Analysis",
    link: "https://arxiv.org/abs/2408.08333"
  },

  {
    id: "paper_003",
    shortName: "Zhang et al. ISSTA",
    fullTitle: "An Empirical Study of AI-Generated Code Quality at ISSTA",
    authors: "Zhang et al.",
    year: "2025",
    focus: "Empirical study of hallucination patterns across multiple LLMs and programming languages",
    hallucTypes: ["Wrong Syntax Confidence", "Non-existent Method"],
    tag: "Empirical Study",
    link: "https://dl.acm.org/doi/10.1145/3650212.3680304"
  },

  {
    id: "paper_004",
    shortName: "HALLUCODE",
    fullTitle: "HALLUCODE: A Benchmark for Hallucination in Code Large Language Models",
    authors: "Liu et al.",
    year: "2024",
    focus: "Benchmark dataset for evaluating hallucination in code LLMs — static analysis based",
    hallucTypes: ["Fabricated Package", "Non-existent Method", "Wrong Syntax Confidence"],
    tag: "Benchmark",
    link: "https://arxiv.org/abs/2408.01364"
  },

  {
    id: "paper_005",
    shortName: "Gao et al. SLR",
    fullTitle: "A Systematic Literature Review on Hallucinations in Large Language Models",
    authors: "Gao et al.",
    year: "2025",
    focus: "Comprehensive SLR covering hallucination taxonomy, detection methods, and mitigation strategies",
    hallucTypes: ["Fabricated Package", "Wrong Syntax Confidence", "Non-existent Method"],
    tag: "Literature Review",
    link: "https://arxiv.org/abs/2401.06796"
  },

  {
    id: "paper_006",
    shortName: "Li et al.",
    fullTitle: "Evaluating and Mitigating Code Hallucinations in Large Language Models",
    authors: "Li et al.",
    year: "2024",
    focus: "Focuses on mitigation strategies — how to reduce hallucinations in LLM code generation",
    hallucTypes: ["Non-existent Method", "Fabricated Package"],
    tag: "Mitigation",
    link: "https://arxiv.org/abs/2408.01697"
  }

];